

OPM_BASE_ADDRESS		= $AFF000 ;  $AF:F000-AF:F0FF
PSG_BASE_ADDRESS		= $AFF100
OPL3_BASE_ADRESS		= $FAE600 ;  $AF:E600-AF:E7FF

; YM2612
OPN2_BASE_ADDRESS		= $AFF200 ;  $AF:F200-AF:F3FF
OPN2_OFFSET_PART_II		= $100


OPN2_22_LFO				= OPN2_BASE_ADDRESS + $22;	LFO enable 	|	LFO frequency
OPN2_23_TIMER_A_H		= OPN2_BASE_ADDRESS + $24;	Timer A MSBs
OPN2_24_TIMER_A_L		= OPN2_BASE_ADDRESS + $25;	Timer A LSBs
OPN2_25_TIMER_B			= OPN2_BASE_ADDRESS + $26;	Timer B
OPN2_27_CHANEL_3_MODE	= OPN2_BASE_ADDRESS + $27;	Ch3 mode 	Reset B 	Reset A 	Enable B 	Enable A 	Load B 	Load A
OPN2_27_TIMER_CONF		= OPN2_BASE_ADDRESS + $27;	Ch3 mode 	Reset B 	Reset A 	Enable B 	Enable A 	Load B 	Load A
OPN2_28_KEY_ON_OFF		= OPN2_BASE_ADDRESS + $28;	Operator Channel
;OPN2_29				= OPN2_BASE_ADDRESS + $29; not used
OPN2_2A_ADC				= OPN2_BASE_ADDRESS + $2A;	DAC
OPN2_2B_ADC_EN			= OPN2_BASE_ADDRESS + $2B;	DAC en

;--------------------------------------------------------------------------------------
;------------------- DT1 (detune) and MUL (multiple) ----------------------------------
;--------------------------------------------------------------------------------------
;
; MUL ranges from 0 to 15 (decimal), and multiplies the overall frequency, with the
; exception that 0 results in multiplication by 1/2. That is, MUL=0 to 15 gives ×1/2,
; ×1, ×2, ... ×15.
;
; DT1 gives small variations from the overall frequency × MUL. The MSB of DT1 is a
; primitive sign bit, and the two LSB’s are magnitude bits. See the next page for a
; diagram.
;
;--------------------------------------------------------------------------------------
OPN2_30_ADSR__DT1_MUL__CH1_OP1		= OPN2_BASE_ADDRESS + $30;	DT1 	MUL
OPN2_31_ADSR__DT1_MUL__CH2_OP1		= OPN2_BASE_ADDRESS + $31;	DT1 	MUL
OPN2_32_ADSR__DT1_MUL__CH3_OP1		= OPN2_BASE_ADDRESS + $32;	DT1 	MUL
OPN2_34_ADSR__DT1_MUL__CH1_OP2		= OPN2_BASE_ADDRESS + $34;	DT1 	MUL
OPN2_35_ADSR__DT1_MUL__CH2_OP2		= OPN2_BASE_ADDRESS + $35;	DT1 	MUL
OPN2_36_ADSR__DT1_MUL__CH3_OP2		= OPN2_BASE_ADDRESS + $36;	DT1 	MUL
OPN2_38_ADSR__DT1_MUL__CH1_OP3		= OPN2_BASE_ADDRESS + $38;	DT1 	MUL
OPN2_39_ADSR__DT1_MUL__CH2_OP3		= OPN2_BASE_ADDRESS + $39;	DT1 	MUL
OPN2_3A_ADSR__DT1_MUL__CH3_OP3		= OPN2_BASE_ADDRESS + $3A;	DT1 	MUL
OPN2_3C_ADSR__DT1_MUL__CH1_OP4		= OPN2_BASE_ADDRESS + $3C;	DT1 	MUL
OPN2_3D_ADSR__DT1_MUL__CH2_OP4		= OPN2_BASE_ADDRESS + $3D;	DT1 	MUL
OPN2_3E_ADSR__DT1_MUL__CH3_OP4		= OPN2_BASE_ADDRESS + $3E;	DT1 	MUL
OPN2_30_ADSR__DT1_MUL__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $30;	DT1 	MUL
OPN2_31_ADSR__DT1_MUL__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $31;	DT1 	MUL
OPN2_32_ADSR__DT1_MUL__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $32;	DT1 	MUL
OPN2_34_ADSR__DT1_MUL__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $34;	DT1 	MUL
OPN2_35_ADSR__DT1_MUL__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $35;	DT1 	MUL
OPN2_36_ADSR__DT1_MUL__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $36;	DT1 	MUL
OPN2_38_ADSR__DT1_MUL__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $38;	DT1 	MUL
OPN2_39_ADSR__DT1_MUL__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $39;	DT1 	MUL
OPN2_3A_ADSR__DT1_MUL__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $3A;	DT1 	MUL
OPN2_3C_ADSR__DT1_MUL__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $3C;	DT1 	MUL
OPN2_3D_ADSR__DT1_MUL__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $3D;	DT1 	MUL
OPN2_3E_ADSR__DT1_MUL__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $3E;	DT1 	MUL
;--------------------------------------------------------------------------------------
;---------------------------------- TL (total level) ----------------------------------
;--------------------------------------------------------------------------------------
;
; TL (total level) represents the envelope’s highest amplitude, with 0 being the largest
; and 127 (decimal) the smallest. A change of one unit is about 0.75 dB.
;
; To make a note softer, only change the TL of the slots (the output operators).
; Changing the other operators will affect the flavor of the note.
;
;--------------------------------------------------------------------------------------
OPN2_40_ADSR__LT__CH1_OP1		= OPN2_BASE_ADDRESS + $40;	LT
OPN2_41_ADSR__LT__CH2_OP1		= OPN2_BASE_ADDRESS + $41;	LT
OPN2_42_ADSR__LT__CH3_OP1		= OPN2_BASE_ADDRESS + $42;	LT
OPN2_44_ADSR__LT__CH1_OP2		= OPN2_BASE_ADDRESS + $44;	LT
OPN2_45_ADSR__LT__CH2_OP2		= OPN2_BASE_ADDRESS + $45;	LT
OPN2_46_ADSR__LT__CH3_OP2		= OPN2_BASE_ADDRESS + $46;	LT
OPN2_48_ADSR__LT__CH1_OP3		= OPN2_BASE_ADDRESS + $48;	LT
OPN2_49_ADSR__LT__CH2_OP3		= OPN2_BASE_ADDRESS + $49;	LT
OPN2_4A_ADSR__LT__CH3_OP3		= OPN2_BASE_ADDRESS + $4A;	LT
OPN2_4C_ADSR__LT__CH1_OP4		= OPN2_BASE_ADDRESS + $4C;	LT
OPN2_4D_ADSR__LT__CH2_OP4		= OPN2_BASE_ADDRESS + $4D;	LT
OPN2_4E_ADSR__LT__CH3_OP4		= OPN2_BASE_ADDRESS + $4E;	LT
OPN2_40_ADSR__LT__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $40;	LT
OPN2_41_ADSR__LT__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $41;	LT
OPN2_42_ADSR__LT__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $42;	LT
OPN2_44_ADSR__LT__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $44;	LT
OPN2_45_ADSR__LT__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $45;	LT
OPN2_46_ADSR__LT__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $46;	LT
OPN2_48_ADSR__LT__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $48;	LT
OPN2_49_ADSR__LT__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $49;	LT
OPN2_4A_ADSR__LT__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $4A;	LT
OPN2_4C_ADSR__LT__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $4C;	LT
OPN2_4D_ADSR__LT__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $4D;	LT
OPN2_4E_ADSR__LT__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $4E;	LT
;--------------------------------------------------------------------------------------
;------------------- RS (rate scaling) and AR (attack rate) ---------------------------
;--------------------------------------------------------------------------------------
;
; AR is the steepness of the initial amplitude rise, shown on page 5.
;
; RS affects AR, D1R, D2R and RR in the same way. RS is the degree to which the envelope
; becomes narrower as the frequency becomes higher.
;
;--------------------------------------------------------------------------------------
OPN2_50_ADSR__SR_AR__CH1_OP1		= OPN2_BASE_ADDRESS + $50;	SR AR
OPN2_51_ADSR__SR_AR__CH2_OP1		= OPN2_BASE_ADDRESS + $51;	SR AR
OPN2_52_ADSR__SR_AR__CH3_OP1		= OPN2_BASE_ADDRESS + $52;	SR AR
OPN2_54_ADSR__SR_AR__CH1_OP2		= OPN2_BASE_ADDRESS + $54;	SR AR
OPN2_55_ADSR__SR_AR__CH2_OP2		= OPN2_BASE_ADDRESS + $55;	SR AR
OPN2_56_ADSR__SR_AR__CH3_OP2		= OPN2_BASE_ADDRESS + $56;	SR AR
OPN2_58_ADSR__SR_AR__CH1_OP3		= OPN2_BASE_ADDRESS + $58;	SR AR
OPN2_59_ADSR__SR_AR__CH2_OP3		= OPN2_BASE_ADDRESS + $59;	SR AR
OPN2_5A_ADSR__SR_AR__CH3_OP3		= OPN2_BASE_ADDRESS + $5A;	SR AR
OPN2_5C_ADSR__SR_AR__CH1_OP4		= OPN2_BASE_ADDRESS + $5C;	SR AR
OPN2_5D_ADSR__SR_AR__CH2_OP4		= OPN2_BASE_ADDRESS + $5D;	SR AR
OPN2_5E_ADSR__SR_AR__CH3_OP4		= OPN2_BASE_ADDRESS + $5E;	SR AR
OPN2_50_ADSR__SR_AR__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $50;	SR AR
OPN2_51_ADSR__SR_AR__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $51;	SR AR
OPN2_52_ADSR__SR_AR__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $52;	SR AR
OPN2_54_ADSR__SR_AR__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $54;	SR AR
OPN2_55_ADSR__SR_AR__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $55;	SR AR
OPN2_56_ADSR__SR_AR__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $56;	SR AR
OPN2_58_ADSR__SR_AR__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $58;	SR AR
OPN2_59_ADSR__SR_AR__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $59;	SR AR
OPN2_5A_ADSR__SR_AR__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $5A;	SR AR
OPN2_5C_ADSR__SR_AR__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $5C;	SR AR
OPN2_5D_ADSR__SR_AR__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $5D;	SR AR
OPN2_5E_ADSR__SR_AR__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $5E;	SR AR
;--------------------------------------------------------------------------------------
;-------------- AM modulation enable amd D1R (first decay rate) -----------------------
;--------------------------------------------------------------------------------------
;
; D1R (first decay rate) is the initial steep amplitude decay rate (see page 4). It is,
; like all rates, 0-31 in value and affected by RS.
;
; AM is the amplitude modulation enable, whether of not this operator will be subject to
; amplitude modulation by the LFO. This bit is not relevant unless both the LFO is
; enabled and register B4′s AMS (amplitude modulation sensitivity) is non-zero.
;
;--------------------------------------------------------------------------------------
OPN2_60_ADSR__AM_D1R__CH1_OP1		= OPN2_BASE_ADDRESS + $60;	AM D1R
OPN2_61_ADSR__AM_D1R__CH2_OP1		= OPN2_BASE_ADDRESS + $61;	AM D1R
OPN2_62_ADSR__AM_D1R__CH3_OP1		= OPN2_BASE_ADDRESS + $62;	AM D1R
OPN2_64_ADSR__AM_D1R__CH1_OP2		= OPN2_BASE_ADDRESS + $64;	AM D1R
OPN2_65_ADSR__AM_D1R__CH2_OP2		= OPN2_BASE_ADDRESS + $65;	AM D1R
OPN2_66_ADSR__AM_D1R__CH3_OP2		= OPN2_BASE_ADDRESS + $66;	AM D1R
OPN2_68_ADSR__AM_D1R__CH1_OP3		= OPN2_BASE_ADDRESS + $68;	AM D1R
OPN2_69_ADSR__AM_D1R__CH2_OP3		= OPN2_BASE_ADDRESS + $69;	AM D1R
OPN2_6A_ADSR__AM_D1R__CH3_OP3		= OPN2_BASE_ADDRESS + $6A;	AM D1R
OPN2_6C_ADSR__AM_D1R__CH1_OP4		= OPN2_BASE_ADDRESS + $6C;	AM D1R
OPN2_6D_ADSR__AM_D1R__CH2_OP4		= OPN2_BASE_ADDRESS + $6D;	AM D1R
OPN2_6E_ADSR__AM_D1R__CH3_OP4		= OPN2_BASE_ADDRESS + $6E;	AM D1R
OPN2_60_ADSR__AM_D1R__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $60;	AM D1R
OPN2_61_ADSR__AM_D1R__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $61;	AM D1R
OPN2_62_ADSR__AM_D1R__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $62;	AM D1R
OPN2_64_ADSR__AM_D1R__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $64;	AM D1R
OPN2_65_ADSR__AM_D1R__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $65;	AM D1R
OPN2_66_ADSR__AM_D1R__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $66;	AM D1R
OPN2_68_ADSR__AM_D1R__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $68;	AM D1R
OPN2_69_ADSR__AM_D1R__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $69;	AM D1R
OPN2_6A_ADSR__AM_D1R__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $6A;	AM D1R
OPN2_6C_ADSR__AM_D1R__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $6C;	AM D1R
OPN2_6D_ADSR__AM_D1R__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $6D;	AM D1R
OPN2_6E_ADSR__AM_D1R__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $6E;	AM D1R
;--------------------------------------------------------------------------------------
;-------------------------- D2R (secondary decay rate) --------------------------------
;--------------------------------------------------------------------------------------
;
; D2R (secondary decay rate) is the long tail off of the sound that continues as long
; as the key is depressed.
;
;--------------------------------------------------------------------------------------
OPN2_70_ADSR__D2R__CH1_OP1		= OPN2_BASE_ADDRESS + $70;	D2R
OPN2_71_ADSR__D2R__CH2_OP1		= OPN2_BASE_ADDRESS + $71;	D2R
OPN2_72_ADSR__D2R__CH3_OP1		= OPN2_BASE_ADDRESS + $72;	D2R
OPN2_74_ADSR__D2R__CH1_OP2		= OPN2_BASE_ADDRESS + $74;	D2R
OPN2_75_ADSR__D2R__CH2_OP2		= OPN2_BASE_ADDRESS + $75;	D2R
OPN2_76_ADSR__D2R__CH3_OP2		= OPN2_BASE_ADDRESS + $76;	D2R
OPN2_78_ADSR__D2R__CH1_OP3		= OPN2_BASE_ADDRESS + $78;	D2R
OPN2_79_ADSR__D2R__CH2_OP3		= OPN2_BASE_ADDRESS + $79;	D2R
OPN2_7A_ADSR__D2R__CH3_OP3		= OPN2_BASE_ADDRESS + $7A;	D2R
OPN2_7C_ADSR__D2R__CH1_OP4		= OPN2_BASE_ADDRESS + $7C;	D2R
OPN2_7D_ADSR__D2R__CH2_OP4		= OPN2_BASE_ADDRESS + $7D;	D2R
OPN2_7E_ADSR__D2R__CH3_OP4		= OPN2_BASE_ADDRESS + $7E;	D2R
OPN2_70_ADSR__D2R__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $70;	D2R
OPN2_71_ADSR__D2R__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $71;	D2R
OPN2_72_ADSR__D2R__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $72;	D2R
OPN2_74_ADSR__D2R__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $74;	D2R
OPN2_75_ADSR__D2R__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $75;	D2R
OPN2_76_ADSR__D2R__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $76;	D2R
OPN2_78_ADSR__D2R__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $78;	D2R
OPN2_79_ADSR__D2R__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $79;	D2R
OPN2_7A_ADSR__D2R__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $7A;	D2R
OPN2_7C_ADSR__D2R__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $7C;	D2R
OPN2_7D_ADSR__D2R__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $7D;	D2R
OPN2_7E_ADSR__D2R__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $7E;	D2R
;--------------------------------------------------------------------------------------
;-------------------------- D2R (secondary decay rate) --------------------------------
;--------------------------------------------------------------------------------------
;
; D2R (secondary decay rate) is the long tail off of the sound that continues as long
; as the key is depressed.
;
;--------------------------------------------------------------------------------------
OPN2_80_ADSR__D1L_RR__CH1_OP1		= OPN2_BASE_ADDRESS + $80;	D1L RR
OPN2_81_ADSR__D1L_RR__CH2_OP1		= OPN2_BASE_ADDRESS + $81;	D1L RR
OPN2_82_ADSR__D1L_RR__CH3_OP1		= OPN2_BASE_ADDRESS + $82;	D1L RR
OPN2_84_ADSR__D1L_RR__CH1_OP2		= OPN2_BASE_ADDRESS + $84;	D1L RR
OPN2_85_ADSR__D1L_RR__CH2_OP2		= OPN2_BASE_ADDRESS + $85;	D1L RR
OPN2_86_ADSR__D1L_RR__CH3_OP2		= OPN2_BASE_ADDRESS + $86;	D1L RR
OPN2_88_ADSR__D1L_RR__CH1_OP3		= OPN2_BASE_ADDRESS + $88;	D1L RR
OPN2_89_ADSR__D1L_RR__CH2_OP3		= OPN2_BASE_ADDRESS + $89;	D1L RR
OPN2_8A_ADSR__D1L_RR__CH3_OP3		= OPN2_BASE_ADDRESS + $8A;	D1L RR
OPN2_8C_ADSR__D1L_RR__CH1_OP4		= OPN2_BASE_ADDRESS + $8C;	D1L RR
OPN2_8D_ADSR__D1L_RR__CH2_OP4		= OPN2_BASE_ADDRESS + $8D;	D1L RR
OPN2_8E_ADSR__D1L_RR__CH3_OP4		= OPN2_BASE_ADDRESS + $8E;	D1L RR
OPN2_80_ADSR__D1L_RR__CH1_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $80;	D1L RR
OPN2_81_ADSR__D1L_RR__CH2_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $81;	D1L RR
OPN2_82_ADSR__D1L_RR__CH3_OP5		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $82;	D1L RR
OPN2_84_ADSR__D1L_RR__CH1_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $84;	D1L RR
OPN2_85_ADSR__D1L_RR__CH2_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $85;	D1L RR
OPN2_86_ADSR__D1L_RR__CH3_OP6		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $86;	D1L RR
OPN2_88_ADSR__D1L_RR__CH1_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $88;	D1L RR
OPN2_89_ADSR__D1L_RR__CH2_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $89;	D1L RR
OPN2_8A_ADSR__D1L_RR__CH3_OP7		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $8A;	D1L RR
OPN2_8C_ADSR__D1L_RR__CH1_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $8C;	D1L RR
OPN2_8D_ADSR__D1L_RR__CH2_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $8D;	D1L RR
OPN2_8E_ADSR__D1L_RR__CH3_OP8		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $8E;	D1L RR
;--------------------------------------------------------------------------------------
;------------------------------------ SSG-EG ------------------------------------------
;--------------------------------------------------------------------------------------
;
; This register is proprietary and should be set to zero.
;
;--------------------------------------------------------------------------------------
OPN2_90_ADSR__D1L_RR__CH1_OP1		= OPN2_BASE_ADDRESS + $90;	D1L RR
OPN2_91_ADSR__D1L_RR__CH2_OP1		= OPN2_BASE_ADDRESS + $91;	D1L RR
OPN2_92_ADSR__D1L_RR__CH3_OP1		= OPN2_BASE_ADDRESS + $92;	D1L RR
OPN2_94_ADSR__D1L_RR__CH1_OP2		= OPN2_BASE_ADDRESS + $94;	D1L RR
OPN2_95_ADSR__D1L_RR__CH2_OP2		= OPN2_BASE_ADDRESS + $95;	D1L RR
OPN2_96_ADSR__D1L_RR__CH3_OP2		= OPN2_BASE_ADDRESS + $96;	D1L RR
OPN2_98_ADSR__D1L_RR__CH1_OP3		= OPN2_BASE_ADDRESS + $98;	D1L RR
OPN2_99_ADSR__D1L_RR__CH2_OP3		= OPN2_BASE_ADDRESS + $99;	D1L RR
OPN2_9A_ADSR__D1L_RR__CH3_OP3		= OPN2_BASE_ADDRESS + $9A;	D1L RR
OPN2_9C_ADSR__D1L_RR__CH1_OP4		= OPN2_BASE_ADDRESS + $9C;	D1L RR
OPN2_9D_ADSR__D1L_RR__CH2_OP4		= OPN2_BASE_ADDRESS + $9D;	D1L RR
OPN2_9E_ADSR__D1L_RR__CH3_OP4		= OPN2_BASE_ADDRESS + $9E;	D1L RR
OPN2_90_ADSR__D1L_RR__CH4_OP1		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $90;	D1L RR
OPN2_91_ADSR__D1L_RR__CH5_OP1		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $91;	D1L RR
OPN2_92_ADSR__D1L_RR__CH6_OP1		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $92;	D1L RR
OPN2_94_ADSR__D1L_RR__CH4_OP2		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $94;	D1L RR
OPN2_95_ADSR__D1L_RR__CH5_OP2		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $95;	D1L RR
OPN2_96_ADSR__D1L_RR__CH6_OP2		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $96;	D1L RR
OPN2_98_ADSR__D1L_RR__CH4_OP3		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $98;	D1L RR
OPN2_99_ADSR__D1L_RR__CH5_OP3		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $99;	D1L RR
OPN2_9A_ADSR__D1L_RR__CH6_OP3		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $9A;	D1L RR
OPN2_9C_ADSR__D1L_RR__CH4_OP4		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $9C;	D1L RR
OPN2_9D_ADSR__D1L_RR__CH5_OP4		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $9D;	D1L RR
OPN2_9E_ADSR__D1L_RR__CH6_OP4		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $9E;	D1L RR
;--------------------------------------------------------------------------------------

OPN2_A0_CH1_FRECANCY_L				= OPN2_BASE_ADDRESS + $A0;	Frequency number LSB
OPN2_A1_CH2_FRECANCY_L				= OPN2_BASE_ADDRESS + $A1;	Frequency number LSB
OPN2_A2_CH3_FRECANCY_L				= OPN2_BASE_ADDRESS + $A2;	Frequency number LSB
OPN2_A2_CH3_FRECANCY_OP1_L			= OPN2_BASE_ADDRESS + $A2;	Frequency number LSB Chanel 3 Operator 1 if special mode
OPN2_A8_CH3_FRECANCY_OP2_L			= OPN2_BASE_ADDRESS + $A8;	Frequency number LSB Chanel 3 Operator 2 if special mode
OPN2_A9_CH3_FRECANCY_OP3_L			= OPN2_BASE_ADDRESS + $A9;	Frequency number LSB Chanel 3 Operator 3 if special mode
OPN2_AA_CH3_FRECANCY_OP4_L			= OPN2_BASE_ADDRESS + $AA;	Frequency number LSB Chanel 3 Operator 4 if special mode
OPN2_A0_CH4_FRECANCY_L				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A0;	Frequency number LSB
OPN2_A1_CH5_FRECANCY_L				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A1;	Frequency number LSB
OPN2_A2_CH6_FRECANCY_L				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A2;	Frequency number LSB

OPN2_A4_CH1_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + $A4;	OCTAVE and Frequency number MSB
OPN2_A5_CH2_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + $A5;	OCTAVE and Frequency number MSB
OPN2_A6_CH3_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + $A6;	OCTAVE and Frequency number MSB
OPN2_A6_CH3_OCTAVE_FRECANCY_OP1_H	= OPN2_BASE_ADDRESS + $A6;	OCTAVE and Frequency number MSB Chanel 3 Operator 1 if special mode
OPN2_AC_CH3_OCTAVE_FRECANCY_OP2_H	= OPN2_BASE_ADDRESS + $AC;	OCTAVE and Frequency number MSB Chanel 3 Operator 2 if special mode
OPN2_AD_CH3_OCTAVE_FRECANCY_OP3_H	= OPN2_BASE_ADDRESS + $AD;	OCTAVE and Frequency number MSB Chanel 3 Operator 3 if special mode
OPN2_AE_CH3_OCTAVE_FRECANCY_OP4_H	= OPN2_BASE_ADDRESS + $AE;	OCTAVE and Frequency number MSB Chanel 3 Operator 4 if special mode
OPN2_A4_CH4_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A4;	OCTAVE and Frequency number MSB
OPN2_A5_CH5_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A5;	OCTAVE and Frequency number MSB
OPN2_A6_CH6_OCTAVE_FRECANCY_H		= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $A6;	OCTAVE and Frequency number MSB

; Feedback is the degree to which operator 1 feeds back into itself.
; The algorithm is the type of inter-operator connection used
OPN2_B0_CH1_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + $B0;
OPN2_B1_CH2_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + $B1;
OPN2_B2_CH3_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + $B2;
OPN2_B0_CH4_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B0;
OPN2_B1_CH5_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B1;
OPN2_B2_CH6_FEEDBACK_ALGO			= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B2;

; Register B4H contains stereo output control and LFO sensitivity control.
OPN2_B4_CH1_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + $B4;
OPN2_B5_CH2_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + $B5;
OPN2_B6_CH3_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + $B6;
OPN2_B4_CH4_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B4;
OPN2_B5_CH5_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B5;
OPN2_B6_CH6_L_R_AMS_FMS				= OPN2_BASE_ADDRESS + OPN2_OFFSET_PART_II + $B6;

;--------------------------------------------------------------------------------------
;--------------------------------------------------------------------------------------
;--------------------------------------------------------------------------------------

OPM_01_TEST					= OPM_BASE_ADDRESS + $01;
OPM_08_KEY_ON_OFF		= OPM_BASE_ADDRESS + $08;
OPM_0F_NE_NFREQ			= OPM_BASE_ADDRESS + $0F;
OPM_10_CLK_A1				= OPM_BASE_ADDRESS + $10;
OPM_11_CLK_A2				= OPM_BASE_ADDRESS + $11;
OPM_12_CLK_B				= OPM_BASE_ADDRESS + $12;
OPM_14_CMS_FLAG_RESET_IRQEN_LOAD	= OPM_BASE_ADDRESS + $14;
OPM_18_LFRQ					= OPM_BASE_ADDRESS + $18;
OPM_19_PMD_AMD			= OPM_BASE_ADDRESS + $19;
OPM_1B_CT_W					= OPM_BASE_ADDRESS + $1B;


OPM_20_A_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $20;
OPM_21_B_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $21;
OPM_22_C_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $22;
OPM_23_D_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $23;
OPM_24_E_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $24;
OPM_25_F_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $25;
OPM_26_G_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $26;
OPM_27_H_RL_FR_CONNECT	= OPM_BASE_ADDRESS + $27;
OPM_28_A_KC							= OPM_BASE_ADDRESS + $28;
OPM_29_B_KC							= OPM_BASE_ADDRESS + $29;
OPM_2A_C_KC							= OPM_BASE_ADDRESS + $2A;
OPM_2B_D_KC							= OPM_BASE_ADDRESS + $2B;
OPM_2C_E_KC							= OPM_BASE_ADDRESS + $2C;
OPM_2D_F_KC							= OPM_BASE_ADDRESS + $2D;
OPM_2E_G_KC							= OPM_BASE_ADDRESS + $2E;
OPM_2F_H_KC							= OPM_BASE_ADDRESS + $2F;
OPM_30_A_KF							= OPM_BASE_ADDRESS + $30;
OPM_31_B_KF							= OPM_BASE_ADDRESS + $31;
OPM_32_C_KF							= OPM_BASE_ADDRESS + $32;
OPM_33_D_KF							= OPM_BASE_ADDRESS + $33;
OPM_34_E_KF							= OPM_BASE_ADDRESS + $34;
OPM_35_F_KF							= OPM_BASE_ADDRESS + $35;
OPM_36_G_KF							= OPM_BASE_ADDRESS + $36;
OPM_37_H_KF							= OPM_BASE_ADDRESS + $37;
OPM_38_A_PMS_AMS				= OPM_BASE_ADDRESS + $38;
OPM_39_B_PMS_AMS				= OPM_BASE_ADDRESS + $39;
OPM_3A_C_PMS_AMS				= OPM_BASE_ADDRESS + $3A;
OPM_3B_D_PMS_AMS				= OPM_BASE_ADDRESS + $3B;
OPM_3C_E_PMS_AMS				= OPM_BASE_ADDRESS + $3C;
OPM_3D_F_PMS_AMS				= OPM_BASE_ADDRESS + $3D;
OPM_3E_G_PMS_AMS				= OPM_BASE_ADDRESS + $3E;
OPM_3F_H_PMS_AMS				= OPM_BASE_ADDRESS + $3F;

OPM_40_A_M1_DT1_MUL			= OPM_BASE_ADDRESS + $40;
OPM_41_B_M1_DT1_MUL			= OPM_BASE_ADDRESS + $41;
OPM_42_C_M1_DT1_MUL			= OPM_BASE_ADDRESS + $42;
OPM_43_D_M1_DT1_MUL			= OPM_BASE_ADDRESS + $43;
OPM_44_E_M1_DT1_MUL			= OPM_BASE_ADDRESS + $44;
OPM_45_F_M1_DT1_MUL			= OPM_BASE_ADDRESS + $45;
OPM_46_G_M1_DT1_MUL			= OPM_BASE_ADDRESS + $46;
OPM_47_H_M1_DT1_MUL			= OPM_BASE_ADDRESS + $47;
OPM_48_A_M2_DT1_MUL			= OPM_BASE_ADDRESS + $48;
OPM_49_B_M2_DT1_MUL			= OPM_BASE_ADDRESS + $49;
OPM_4A_C_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4A;
OPM_4B_D_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4B;
OPM_4C_E_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4C;
OPM_4D_F_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4D;
OPM_4E_G_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4E;
OPM_4F_H_M2_DT1_MUL			= OPM_BASE_ADDRESS + $4F;
OPM_50_A_C1_DT1_MUL			= OPM_BASE_ADDRESS + $50;
OPM_51_B_C1_DT1_MUL			= OPM_BASE_ADDRESS + $51;
OPM_52_C_C1_DT1_MUL			= OPM_BASE_ADDRESS + $52;
OPM_53_D_C1_DT1_MUL			= OPM_BASE_ADDRESS + $53;
OPM_54_E_C1_DT1_MUL			= OPM_BASE_ADDRESS + $54;
OPM_55_F_C1_DT1_MUL			= OPM_BASE_ADDRESS + $55;
OPM_56_G_C1_DT1_MUL			= OPM_BASE_ADDRESS + $56;
OPM_57_H_C1_DT1_MUL			= OPM_BASE_ADDRESS + $57;
OPM_58_A_C2_DT1_MUL			= OPM_BASE_ADDRESS + $58;
OPM_59_B_C2_DT1_MUL			= OPM_BASE_ADDRESS + $59;
OPM_5A_C_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5A;
OPM_5B_D_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5B;
OPM_5C_E_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5C;
OPM_5D_F_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5D;
OPM_5E_G_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5E;
OPM_5F_H_C2_DT1_MUL			= OPM_BASE_ADDRESS + $5F;

OPM_60_A_M1_TL				= OPM_BASE_ADDRESS + $60;
OPM_61_B_M1_TL				= OPM_BASE_ADDRESS + $61;
OPM_62_C_M1_TL				= OPM_BASE_ADDRESS + $62;
OPM_63_D_M1_TL				= OPM_BASE_ADDRESS + $63;
OPM_64_E_M1_TL				= OPM_BASE_ADDRESS + $64;
OPM_65_F_M1_TL				= OPM_BASE_ADDRESS + $65;
OPM_66_G_M1_TL				= OPM_BASE_ADDRESS + $66;
OPM_67_H_M1_TL				= OPM_BASE_ADDRESS + $67;
OPM_68_A_M2_TL				= OPM_BASE_ADDRESS + $68;
OPM_69_B_M2_TL				= OPM_BASE_ADDRESS + $69;
OPM_6A_C_M2_TL				= OPM_BASE_ADDRESS + $6A;
OPM_6B_D_M2_TL				= OPM_BASE_ADDRESS + $6B;
OPM_6C_E_M2_TL				= OPM_BASE_ADDRESS + $6C;
OPM_6D_F_M2_TL				= OPM_BASE_ADDRESS + $6D;
OPM_6E_G_M2_TL				= OPM_BASE_ADDRESS + $6E;
OPM_6F_H_M2_TL				= OPM_BASE_ADDRESS + $6F;
OPM_70_A_C1_TL				= OPM_BASE_ADDRESS + $70;
OPM_71_B_C1_TL				= OPM_BASE_ADDRESS + $71;
OPM_72_C_C1_TL				= OPM_BASE_ADDRESS + $72;
OPM_73_D_C1_TL				= OPM_BASE_ADDRESS + $73;
OPM_74_E_C1_TL				= OPM_BASE_ADDRESS + $74;
OPM_75_F_C1_TL				= OPM_BASE_ADDRESS + $75;
OPM_76_G_C1_TL				= OPM_BASE_ADDRESS + $76;
OPM_77_H_C1_TL				= OPM_BASE_ADDRESS + $77;
OPM_78_A_C2_TL				= OPM_BASE_ADDRESS + $78;
OPM_79_B_C2_TL				= OPM_BASE_ADDRESS + $79;
OPM_7A_C_C2_TL				= OPM_BASE_ADDRESS + $7A;
OPM_7B_D_C2_TL				= OPM_BASE_ADDRESS + $7B;
OPM_7C_E_C2_TL				= OPM_BASE_ADDRESS + $7C;
OPM_7D_F_C2_TL				= OPM_BASE_ADDRESS + $7D;
OPM_7E_G_C2_TL				= OPM_BASE_ADDRESS + $7E;
OPM_7F_H_C2_TL				= OPM_BASE_ADDRESS + $7F;

OPM_80_A_M1_KS_AR			= OPM_BASE_ADDRESS + $80;
OPM_81_B_M1_KS_AR			= OPM_BASE_ADDRESS + $81;
OPM_82_C_M1_KS_AR			= OPM_BASE_ADDRESS + $82;
OPM_83_D_M1_KS_AR			= OPM_BASE_ADDRESS + $83;
OPM_84_E_M1_KS_AR			= OPM_BASE_ADDRESS + $84;
OPM_85_F_M1_KS_AR			= OPM_BASE_ADDRESS + $85;
OPM_86_G_M1_KS_AR			= OPM_BASE_ADDRESS + $86;
OPM_87_H_M1_KS_AR			= OPM_BASE_ADDRESS + $87;
OPM_88_A_M2_KS_AR			= OPM_BASE_ADDRESS + $88;
OPM_89_B_M2_KS_AR			= OPM_BASE_ADDRESS + $89;
OPM_8A_C_M2_KS_AR			= OPM_BASE_ADDRESS + $8A;
OPM_8B_D_M2_KS_AR			= OPM_BASE_ADDRESS + $8B;
OPM_8C_E_M2_KS_AR			= OPM_BASE_ADDRESS + $8C;
OPM_8D_F_M2_KS_AR			= OPM_BASE_ADDRESS + $8D;
OPM_8E_G_M2_KS_AR			= OPM_BASE_ADDRESS + $8E;
OPM_8F_H_M2_KS_AR			= OPM_BASE_ADDRESS + $8F;
OPM_90_A_C1_KS_AR			= OPM_BASE_ADDRESS + $90;
OPM_91_B_C1_KS_AR			= OPM_BASE_ADDRESS + $91;
OPM_92_C_C1_KS_AR			= OPM_BASE_ADDRESS + $92;
OPM_93_D_C1_KS_AR			= OPM_BASE_ADDRESS + $93;
OPM_94_E_C1_KS_AR			= OPM_BASE_ADDRESS + $94;
OPM_95_F_C1_KS_AR			= OPM_BASE_ADDRESS + $95;
OPM_96_G_C1_KS_AR			= OPM_BASE_ADDRESS + $96;
OPM_97_H_C1_KS_AR			= OPM_BASE_ADDRESS + $97;
OPM_98_A_C2_KS_AR			= OPM_BASE_ADDRESS + $98;
OPM_99_B_C2_KS_AR			= OPM_BASE_ADDRESS + $99;
OPM_9A_C_C2_KS_AR			= OPM_BASE_ADDRESS + $9A;
OPM_9B_D_C2_KS_AR			= OPM_BASE_ADDRESS + $9B;
OPM_9C_E_C2_KS_AR			= OPM_BASE_ADDRESS + $9C;
OPM_9D_F_C2_KS_AR			= OPM_BASE_ADDRESS + $9D;
OPM_9E_G_C2_KS_AR			= OPM_BASE_ADDRESS + $9E;
OPM_9F_H_C2_KS_AR			= OPM_BASE_ADDRESS + $9F;

OPM_A0_A_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A0;
OPM_A1_B_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A1;
OPM_A2_C_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A2;
OPM_A3_D_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A3;
OPM_A4_E_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A4;
OPM_A5_F_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A5;
OPM_A6_G_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A6;
OPM_A7_H_M1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A7;
OPM_A8_A_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A8;
OPM_A9_B_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $A9;
OPM_AA_C_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AA;
OPM_AB_D_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AB;
OPM_AC_E_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AC;
OPM_AD_F_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AD;
OPM_AE_G_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AE;
OPM_AF_H_M2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $AF;
OPM_B0_A_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B0;
OPM_B1_B_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B1;
OPM_B2_C_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B2;
OPM_B3_D_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B3;
OPM_B4_E_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B4;
OPM_B5_F_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B5;
OPM_B6_G_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B6;
OPM_B7_H_C1_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B7;
OPM_B8_A_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B8;
OPM_B9_B_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $B9;
OPM_BA_C_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BA;
OPM_BB_D_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BB;
OPM_BC_E_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BC;
OPM_BD_F_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BD;
OPM_BE_G_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BE;
OPM_BF_H_C2_AMS_EN_D1R		= OPM_BASE_ADDRESS + $BF;

OPM_C0_A_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C0;
OPM_C1_B_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C1;
OPM_C2_C_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C2;
OPM_C3_D_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C3;
OPM_C4_E_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C4;
OPM_C5_F_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C5;
OPM_C6_G_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C6;
OPM_C7_H_M1_DT2_D2R			= OPM_BASE_ADDRESS + $C7;
OPM_C8_A_M2_DT2_D2R			= OPM_BASE_ADDRESS + $C8;
OPM_C9_B_M2_DT2_D2R			= OPM_BASE_ADDRESS + $C9;
OPM_CA_C_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CA;
OPM_CB_D_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CB;
OPM_CC_E_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CC;
OPM_CD_F_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CD;
OPM_CE_G_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CE;
OPM_CF_H_M2_DT2_D2R			= OPM_BASE_ADDRESS + $CF;
OPM_D0_A_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D0;
OPM_D1_B_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D1;
OPM_D2_C_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D2;
OPM_D3_D_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D3;
OPM_D4_E_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D4;
OPM_D5_F_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D5;
OPM_D6_G_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D6;
OPM_D7_H_C1_DT2_D2R			= OPM_BASE_ADDRESS + $D7;
OPM_D8_A_C2_DT2_D2R			= OPM_BASE_ADDRESS + $D8;
OPM_D9_B_C2_DT2_D2R			= OPM_BASE_ADDRESS + $D9;
OPM_DA_C_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DA;
OPM_DB_D_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DB;
OPM_DC_E_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DC;
OPM_DD_F_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DD;
OPM_DE_G_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DE;
OPM_DF_H_C2_DT2_D2R			= OPM_BASE_ADDRESS + $DF;

OPM_E0_A_M1_D1L_RR			= OPM_BASE_ADDRESS + $E0;
OPM_E1_B_M1_D1L_RR			= OPM_BASE_ADDRESS + $E1;
OPM_E2_C_M1_D1L_RR			= OPM_BASE_ADDRESS + $E2;
OPM_E3_D_M1_D1L_RR			= OPM_BASE_ADDRESS + $E3;
OPM_E4_E_M1_D1L_RR			= OPM_BASE_ADDRESS + $E4;
OPM_E5_F_M1_D1L_RR			= OPM_BASE_ADDRESS + $E5;
OPM_E6_G_M1_D1L_RR			= OPM_BASE_ADDRESS + $E6;
OPM_E7_H_M1_D1L_RR			= OPM_BASE_ADDRESS + $E7;
OPM_E8_A_M2_D1L_RR			= OPM_BASE_ADDRESS + $E8;
OPM_E9_B_M2_D1L_RR			= OPM_BASE_ADDRESS + $E9;
OPM_EA_C_M2_D1L_RR			= OPM_BASE_ADDRESS + $EA;
OPM_EB_D_M2_D1L_RR			= OPM_BASE_ADDRESS + $EB;
OPM_EC_E_M2_D1L_RR			= OPM_BASE_ADDRESS + $EC;
OPM_ED_F_M2_D1L_RR			= OPM_BASE_ADDRESS + $ED;
OPM_EE_G_M2_D1L_RR			= OPM_BASE_ADDRESS + $EE;
OPM_EF_H_M2_D1L_RR			= OPM_BASE_ADDRESS + $EF;
OPM_F0_A_C1_D1L_RR			= OPM_BASE_ADDRESS + $F0;
OPM_F1_B_C1_D1L_RR			= OPM_BASE_ADDRESS + $F1;
OPM_F2_C_C1_D1L_RR			= OPM_BASE_ADDRESS + $F2;
OPM_F3_D_C1_D1L_RR			= OPM_BASE_ADDRESS + $F3;
OPM_F4_E_C1_D1L_RR			= OPM_BASE_ADDRESS + $F4;
OPM_F5_F_C1_D1L_RR			= OPM_BASE_ADDRESS + $F5;
OPM_F6_G_C1_D1L_RR			= OPM_BASE_ADDRESS + $F6;
OPM_F7_H_C1_D1L_RR			= OPM_BASE_ADDRESS + $F7;
OPM_F8_A_C2_D1L_RR			= OPM_BASE_ADDRESS + $F8;
OPM_F9_B_C2_D1L_RR			= OPM_BASE_ADDRESS + $F9;
OPM_FA_C_C2_D1L_RR			= OPM_BASE_ADDRESS + $FA;
OPM_FB_D_C2_D1L_RR			= OPM_BASE_ADDRESS + $FB;
OPM_FC_E_C2_D1L_RR			= OPM_BASE_ADDRESS + $FC;
OPM_FD_F_C2_D1L_RR			= OPM_BASE_ADDRESS + $FD;
OPM_FE_G_C2_D1L_RR			= OPM_BASE_ADDRESS + $FE;
OPM_FF_H_C2_D1L_RR			= OPM_BASE_ADDRESS + $FF;
